import type { HTMLElement } from '../types/editor'

// 쇼핑몰 상세 페이지 샘플 템플릿 - 프리미엄 무선 이어폰
export const SAMPLE_TEMPLATE: HTMLElement[] = [
  // 1. 상품명 & 가격 헤더
  {
    id: 'header-product',
    type: 'header',
    tagName: 'header',
    style: {
      backgroundColor: '#ffffff',
      padding: '50px 20px',
      textAlign: 'center',
      borderBottom: '1px solid #e5e5e5',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'product-title',
    type: 'h1',
    tagName: 'h1',
    textContent: '프리미엄 노이즈캔슬링 무선 이어폰 PRO',
    style: {
      fontSize: '36px',
      fontWeight: 'bold',
      color: '#111111',
      margin: '0 0 20px 0',
      lineHeight: '1.3',
    },
    children: [],
    parentId: 'header-product',
  },
  {
    id: 'product-subtitle',
    type: 'p',
    tagName: 'p',
    textContent: '완벽한 음질, 최상의 착용감, 프리미엄 라이프스타일',
    style: {
      fontSize: '18px',
      color: '#666666',
      margin: '0 0 30px 0',
    },
    children: [],
    parentId: 'header-product',
  },
  {
    id: 'product-price',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#f8f8f8',
      padding: '20px',
      borderRadius: '8px',
      display: 'inline-block',
    },
    children: [],
    parentId: 'header-product',
  },
  {
    id: 'price-original',
    type: 'p',
    tagName: 'p',
    textContent: '정가: 299,000원',
    style: {
      fontSize: '16px',
      color: '#999999',
      textDecoration: 'line-through',
      margin: '0 0 8px 0',
    },
    children: [],
    parentId: 'product-price',
  },
  {
    id: 'price-sale',
    type: 'p',
    tagName: 'p',
    textContent: '특별가: 199,000원 (33% 할인)',
    style: {
      fontSize: '28px',
      color: '#e74c3c',
      fontWeight: 'bold',
      margin: '0',
    },
    children: [],
    parentId: 'product-price',
  },

  // 2. 메인 이미지 섹션
  {
    id: 'section-main-image',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#f5f5f5',
      padding: '80px 20px',
      textAlign: 'center',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'main-image',
    type: 'img',
    tagName: 'img',
    src: 'https://picsum.photos/seed/earbuds-main/600/600',
    alt: '프리미엄 무선 이어폰 메인 이미지',
    style: {
      width: '100%',
      maxWidth: '600px',
      height: 'auto',
      margin: '0 auto',
      borderRadius: '12px',
      display: 'block',
    },
    children: [],
    parentId: 'section-main-image',
  },

  // 3. 핵심 특징 섹션
  {
    id: 'section-features',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#ffffff',
      padding: '80px 20px',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'features-title',
    type: 'h2',
    tagName: 'h2',
    textContent: '왜 이 제품을 선택해야 할까요?',
    style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: '#111111',
      textAlign: 'center',
      marginBottom: '50px',
    },
    children: [],
    parentId: 'section-features',
  },
  {
    id: 'feature-1',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#f0f7ff',
      padding: '30px',
      borderRadius: '8px',
      marginBottom: '20px',
      borderLeft: '4px solid #3498db',
    },
    children: [],
    parentId: 'section-features',
  },
  {
    id: 'feature-1-title',
    type: 'h3',
    tagName: 'h3',
    textContent: '🎧 프리미엄 ANC 노이즈캔슬링',
    style: {
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#3498db',
      margin: '0 0 12px 0',
    },
    children: [],
    parentId: 'feature-1',
  },
  {
    id: 'feature-1-desc',
    type: 'p',
    tagName: 'p',
    textContent: '최대 -40dB의 강력한 노이즈 캔슬링으로 주변 소음을 완벽하게 차단합니다. 지하철, 카페, 사무실 어디서나 나만의 공간을 만들어보세요.',
    style: {
      fontSize: '16px',
      color: '#555555',
      lineHeight: '1.7',
      margin: '0',
    },
    children: [],
    parentId: 'feature-1',
  },
  {
    id: 'feature-2',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#f0fff4',
      padding: '30px',
      borderRadius: '8px',
      marginBottom: '20px',
      borderLeft: '4px solid #27ae60',
    },
    children: [],
    parentId: 'section-features',
  },
  {
    id: 'feature-2-title',
    type: 'h3',
    tagName: 'h3',
    textContent: '🔋 초장시간 배터리',
    style: {
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#27ae60',
      margin: '0 0 12px 0',
    },
    children: [],
    parentId: 'feature-2',
  },
  {
    id: 'feature-2-desc',
    type: 'p',
    tagName: 'p',
    textContent: '단 한 번의 충전으로 최대 30시간 연속 재생! 충전 케이스 포함 시 80시간 이상 사용 가능합니다. 급속 충전으로 10분 충전에 4시간 재생.',
    style: {
      fontSize: '16px',
      color: '#555555',
      lineHeight: '1.7',
      margin: '0',
    },
    children: [],
    parentId: 'feature-2',
  },
  {
    id: 'feature-3',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#fff5f5',
      padding: '30px',
      borderRadius: '8px',
      marginBottom: '20px',
      borderLeft: '4px solid #e74c3c',
    },
    children: [],
    parentId: 'section-features',
  },
  {
    id: 'feature-3-title',
    type: 'h3',
    tagName: 'h3',
    textContent: '🎵 Hi-Fi 오디오 품질',
    style: {
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#e74c3c',
      margin: '0 0 12px 0',
    },
    children: [],
    parentId: 'feature-3',
  },
  {
    id: 'feature-3-desc',
    type: 'p',
    tagName: 'p',
    textContent: '10mm 다이나믹 드라이버와 AAC/aptX HD 코덱 지원으로 스튜디오급 음질을 경험하세요. 깊은 저음부터 맑은 고음까지 완벽하게 재현합니다.',
    style: {
      fontSize: '16px',
      color: '#555555',
      lineHeight: '1.7',
      margin: '0',
    },
    children: [],
    parentId: 'feature-3',
  },

  // 4. 상세 설명 섹션
  {
    id: 'section-details',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#f9f9f9',
      padding: '80px 20px',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'details-title',
    type: 'h2',
    tagName: 'h2',
    textContent: '상세 사양',
    style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: '#111111',
      textAlign: 'center',
      marginBottom: '40px',
    },
    children: [],
    parentId: 'section-details',
  },
  {
    id: 'details-content',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#ffffff',
      padding: '40px',
      borderRadius: '8px',
      maxWidth: '700px',
      margin: '0 auto',
    },
    children: [],
    parentId: 'section-details',
  },
  {
    id: 'detail-1',
    type: 'p',
    tagName: 'p',
    textContent: '• 블루투스 버전: 5.3 (최대 연결 거리 15m)',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0 0 12px 0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },
  {
    id: 'detail-2',
    type: 'p',
    tagName: 'p',
    textContent: '• 드라이버: 10mm 다이나믹 드라이버',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0 0 12px 0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },
  {
    id: 'detail-3',
    type: 'p',
    tagName: 'p',
    textContent: '• 노이즈 캔슬링: 하이브리드 ANC (-40dB)',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0 0 12px 0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },
  {
    id: 'detail-4',
    type: 'p',
    tagName: 'p',
    textContent: '• 배터리: 이어폰 30시간 + 케이스 50시간',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0 0 12px 0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },
  {
    id: 'detail-5',
    type: 'p',
    tagName: 'p',
    textContent: '• 방수: IPX5 등급 (생활 방수)',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0 0 12px 0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },
  {
    id: 'detail-6',
    type: 'p',
    tagName: 'p',
    textContent: '• 무게: 이어폰 5.5g (편당) / 케이스 45g',
    style: {
      fontSize: '16px',
      color: '#333333',
      lineHeight: '2',
      margin: '0',
      paddingLeft: '10px',
    },
    children: [],
    parentId: 'details-content',
  },

  // 5. 이미지 갤러리 섹션
  {
    id: 'section-gallery',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#ffffff',
      padding: '80px 20px',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'gallery-title',
    type: 'h2',
    tagName: 'h2',
    textContent: '상품 이미지 갤러리',
    style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: '#111111',
      textAlign: 'center',
      marginBottom: '50px',
    },
    children: [],
    parentId: 'section-gallery',
  },
  {
    id: 'gallery-image-1',
    type: 'img',
    tagName: 'img',
    src: 'https://picsum.photos/seed/earbuds-wearing/800/400',
    alt: '이어폰 착용 이미지',
    style: {
      width: '100%',
      height: 'auto',
      marginBottom: '20px',
      borderRadius: '8px',
      display: 'block',
    },
    children: [],
    parentId: 'section-gallery',
  },
  {
    id: 'gallery-image-2',
    type: 'img',
    tagName: 'img',
    src: 'https://picsum.photos/seed/earbuds-detail/800/400',
    alt: '이어폰 디테일 이미지',
    style: {
      width: '100%',
      height: 'auto',
      marginBottom: '20px',
      borderRadius: '8px',
      display: 'block',
    },
    children: [],
    parentId: 'section-gallery',
  },
  {
    id: 'gallery-image-3',
    type: 'img',
    tagName: 'img',
    src: 'https://picsum.photos/seed/earbuds-colors/800/400',
    alt: '이어폰 색상 옵션 이미지',
    style: {
      width: '100%',
      height: 'auto',
      marginBottom: '20px',
      borderRadius: '8px',
      display: 'block',
    },
    children: [],
    parentId: 'section-gallery',
  },

  // 6. 구매 정보 섹션
  {
    id: 'section-purchase',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#3498db',
      padding: '60px 20px',
      textAlign: 'center',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'purchase-title',
    type: 'h2',
    tagName: 'h2',
    textContent: '지금 바로 구매하세요!',
    style: {
      fontSize: '36px',
      fontWeight: 'bold',
      color: '#ffffff',
      margin: '0 0 20px 0',
    },
    children: [],
    parentId: 'section-purchase',
  },
  {
    id: 'purchase-desc',
    type: 'p',
    tagName: 'p',
    textContent: '✓ 무료배송  ✓ 30일 무료 반품  ✓ 1년 A/S 보증',
    style: {
      fontSize: '18px',
      color: '#ffffff',
      margin: '0 0 30px 0',
    },
    children: [],
    parentId: 'section-purchase',
  },
  {
    id: 'purchase-button',
    type: 'button',
    tagName: 'button',
    textContent: '구매하기',
    style: {
      backgroundColor: '#ffffff',
      color: '#3498db',
      padding: '18px 60px',
      fontSize: '20px',
      fontWeight: 'bold',
      border: 'none',
      borderRadius: '50px',
      cursor: 'pointer',
    },
    children: [],
    parentId: 'section-purchase',
  },

  // 7. 고객 후기 섹션
  {
    id: 'section-reviews',
    type: 'section',
    tagName: 'section',
    style: {
      backgroundColor: '#f9f9f9',
      padding: '80px 20px',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'reviews-title',
    type: 'h2',
    tagName: 'h2',
    textContent: '고객 후기',
    style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: '#111111',
      textAlign: 'center',
      marginBottom: '50px',
    },
    children: [],
    parentId: 'section-reviews',
  },
  {
    id: 'review-1',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#ffffff',
      padding: '30px',
      borderRadius: '8px',
      marginBottom: '20px',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    children: [],
    parentId: 'section-reviews',
  },
  {
    id: 'review-1-rating',
    type: 'p',
    tagName: 'p',
    textContent: '⭐⭐⭐⭐⭐ 5.0',
    style: {
      fontSize: '18px',
      color: '#f39c12',
      margin: '0 0 12px 0',
      fontWeight: 'bold',
    },
    children: [],
    parentId: 'review-1',
  },
  {
    id: 'review-1-text',
    type: 'p',
    tagName: 'p',
    textContent: '음질이 정말 좋아요! 노이즈캔슬링도 완벽하고 배터리도 오래가서 매우 만족합니다. 가격 대비 최고의 선택이었어요.',
    style: {
      fontSize: '16px',
      color: '#555555',
      lineHeight: '1.7',
      margin: '0 0 12px 0',
    },
    children: [],
    parentId: 'review-1',
  },
  {
    id: 'review-1-author',
    type: 'p',
    tagName: 'p',
    textContent: '- 김**님',
    style: {
      fontSize: '14px',
      color: '#999999',
      margin: '0',
      textAlign: 'right',
    },
    children: [],
    parentId: 'review-1',
  },
  {
    id: 'review-2',
    type: 'div',
    tagName: 'div',
    style: {
      backgroundColor: '#ffffff',
      padding: '30px',
      borderRadius: '8px',
      marginBottom: '20px',
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    children: [],
    parentId: 'section-reviews',
  },
  {
    id: 'review-2-rating',
    type: 'p',
    tagName: 'p',
    textContent: '⭐⭐⭐⭐⭐ 5.0',
    style: {
      fontSize: '18px',
      color: '#f39c12',
      margin: '0 0 12px 0',
      fontWeight: 'bold',
    },
    children: [],
    parentId: 'review-2',
  },
  {
    id: 'review-2-text',
    type: 'p',
    tagName: 'p',
    textContent: '착용감이 편하고 디자인도 세련되어요. 출퇴근할 때 매일 사용하는데 하루종일 써도 귀가 안 아파요. 강력 추천합니다!',
    style: {
      fontSize: '16px',
      color: '#555555',
      lineHeight: '1.7',
      margin: '0 0 12px 0',
    },
    children: [],
    parentId: 'review-2',
  },
  {
    id: 'review-2-author',
    type: 'p',
    tagName: 'p',
    textContent: '- 이**님',
    style: {
      fontSize: '14px',
      color: '#999999',
      margin: '0',
      textAlign: 'right',
    },
    children: [],
    parentId: 'review-2',
  },

  // 8. 푸터
  {
    id: 'footer-info',
    type: 'footer',
    tagName: 'footer',
    style: {
      backgroundColor: '#2c3e50',
      color: '#ecf0f1',
      padding: '50px 20px',
      textAlign: 'center',
    },
    children: [],
    parentId: null,
  },
  {
    id: 'footer-company',
    type: 'p',
    tagName: 'p',
    textContent: '프리미엄 오디오 스토어',
    style: {
      fontSize: '20px',
      fontWeight: 'bold',
      margin: '0 0 20px 0',
    },
    children: [],
    parentId: 'footer-info',
  },
  {
    id: 'footer-contact',
    type: 'p',
    tagName: 'p',
    textContent: '고객센터: 1588-0000 | 이메일: support@premium-audio.com',
    style: {
      fontSize: '14px',
      color: '#95a5a6',
      margin: '0 0 10px 0',
    },
    children: [],
    parentId: 'footer-info',
  },
  {
    id: 'footer-copyright',
    type: 'p',
    tagName: 'p',
    textContent: '© 2025 Premium Audio Store. All rights reserved.',
    style: {
      fontSize: '12px',
      color: '#7f8c8d',
      margin: '0',
    },
    children: [],
    parentId: 'footer-info',
  },
]

// 부모-자식 관계를 기반으로 children 배열을 채우는 함수
export function buildElementTree(elements: HTMLElement[]): HTMLElement[] {
  const elementMap = new Map(elements.map((el) => [el.id, { ...el }]))

  // children 배열 초기화
  elementMap.forEach((el) => {
    el.children = []
  })

  // 부모-자식 관계 구축
  elementMap.forEach((el) => {
    if (el.parentId) {
      const parent = elementMap.get(el.parentId)
      if (parent) {
        parent.children.push(el)
      }
    }
  })

  // 최상위 요소만 반환 (parentId가 null인 요소)
  return Array.from(elementMap.values()).filter((el) => el.parentId === null)
}
